### ISSUE TITLE
tsp2.0 reanalysis tasks

### ISSUE THREAD

**Issue by jwbowers** [sbstusa/researchsupportsquad#3]
- [x] Assess/edit the abstract and design (write our own sense of the design and analysis, maybe some preliminary data setup and cleaning.)
- [ ] Get comments from project owner

**Comment by PTesta** [comment]
- Exported the document into a google doc for shared editing
- Created a "tsp" repo on github with some code looking at the data
- Added comments to the current abstract and accepted most of tah96's edits which seemed sensible. It looks like the point estimates and intervals for the graph are not regression adjusted predictions but just straight up sample estimates, which I think makes more sense. Only thing would be to adjust for mutliple comparisons/ construct family wise confidence intervals...
- Happy to write up comments and flesh out the tsp_reanalysis.Rmd; should I send them to Will Tucker or tah96 or Nate?

**Comment by PTesta** [comment]
Wrote up a rough draft of analysis plan, saved in the reanalysis drive of the subfolder. Some general thoughts/questions

1. It looks like there are some strange outliers (e.g. 16 people contributing at 100 percent), should we do a separate analysis excluding cases above a threshold?
2. It seems like in addition to comparing proportions and means we might do some distributional comparisons first
3. I've left out any discussion of Branch of Service and Military grade. It looks like the figures in the initial abstract are done without adjusting for these covariates; including them as fixed effects improves the fit, but with 70,000 cases per cell we're not really underpowered, so it seems like presenting the unadjusted results in the abstract might be the easiest solution

If the analysis plan makes sense, I'll clean up the code in the tsp_reanalysis.Rmd file
