### ISSUE TITLE
onboarding training planning

### ISSUE THREAD

**Issue by jwbowers** [sbstusa/researchsupportsquad#9]
A place to discuss this.

**Comment by PTesta** [comment]
It seems like there are two types of things/expertise we can provide:

1. An explication of the logic of experimental design and causal inference ("Why experiments")
2. An introduction to the basic tools we use to conduct this analysis at SBST ("How to analyze experiments")

So assuming we have perhaps an hour for each, maybe you could give the broad overview of why SBST does what does with randomized experiments and I could give a brief intro into the software (R Studio) and the SOP we're developing.

Does that make sense or am I completely off-base on this? I guess I have some questions like: Who is the audience? New fellows? How much background do they have? What's the general goal of the on-boarding process?
